apiVersion: v1
kind: Secret
metadata:
  name: user-opaque
type: Opaque
data:
  DB_USER: c2E=
  DB_PASS: VGVjaENoYWxsZW5nZUAyMDI2
  JWT_SECRET: MDdhZmFmZmQtMDlmZS00OTBhLWFlMmYtM2RlOGZjYThiMzA2
  RABBITMQ_PASS: Z3Vlc3Q=
  RABBITMQ_USER: Z3Vlc3Q=